import { validateResumeData } from '../../web/shared/model.mjs';
import { AppError } from '../errors.mjs';
import { escapeLatex as text, renderRichText } from './text.mjs';

const TITLES = {
  'zh-CN': { education: '教育经历', experience: '工作经历', projects: '项目经历', skills: '专业技能', awards: '荣誉奖项', social: '社会经历' },
  en: { education: 'Education', experience: 'Experience', projects: 'Projects', skills: 'Skills', awards: 'Awards', social: 'Social Engagements' },
};
const ICONS = { phone: '\\resumePhoneIcon', email: '\\resumeEmailIcon', wechat: '\\resumeChatIcon', url: '\\resumeLinkIcon' };
const LABELS = { 'zh-CN': { phone: '电话', email: '邮箱', wechat: '微信', url: '网站' }, en: { phone: 'Phone', email: 'Email', wechat: 'WeChat', url: 'Website' } };
const joined = values => values.filter(Boolean).map(text).join(' \\textbar{} ');
const paragraph = value => value ? `${value}\\par\n` : '';
function bullets(items) {
  const values = items.map(renderRichText).filter(Boolean);
  return values.length ? `\\begin{itemize}\n${values.map(value => `\\item ${value}`).join('\n')}\n\\end{itemize}\n` : '';
}
function heading(title, period) {
  return `\\resumeHeading{${title}}{${text(period)}}\n`;
}
function itemTex(key, item) {
  switch (key) {
    case 'education':
      return heading(text(item.school), item.period) + paragraph(joined([item.degree, item.major])) + bullets(item.bullets);
    case 'experience':
      return heading(text(item.organization), item.period) + paragraph(joined([item.role, item.location])) + bullets(item.bullets);
    case 'projects': {
      const title = item.url ? renderRichText([{ text: item.name, bold: false, url: item.url }]) : text(item.name);
      return heading(title, item.period) + paragraph(joined([item.role, item.techStack])) + paragraph(renderRichText(item.summary)) + bullets(item.bullets);
    }
    case 'skills':
      return `\\resumeSkill{${text(item.category)}}{${renderRichText(item.content)}}\n`;
    case 'awards':
      return heading(text(item.name), item.period) + paragraph(text(item.issuer)) + paragraph(renderRichText(item.description));
    case 'social':
      return heading(text(item.organization), item.period) + paragraph(text(item.role)) + bullets(item.bullets);
    default: throw new AppError('INVALID_DATA', '未知的简历模块');
  }
}
function profileTex(data) {
  const profile = data.profile;
  const name = text(profile.name) + (profile.alternateName ? ` (${text(profile.alternateName)})` : '');
  const contacts = profile.contacts.map(contact => {
    const label = text(contact.label || LABELS[data.language][contact.type]);
    // Treat the entire email field as a recipient, never as mailto query or
    // fragment syntax. Display the original value while encoding URI bytes.
    const url = contact.type === 'url' ? contact.value
      : contact.type === 'email' && contact.value.trim()
        ? `mailto:${encodeURIComponent(contact.value).replace(/%40/giu, '@')}` : null;
    const value = url ? renderRichText([{ text: contact.value, bold: false, url }]) : text(contact.value);
    return `\\resumeContact{${label}}{${ICONS[contact.type]}} ${value}`;
  });
  return `{\\LARGE\\bfseries ${name}}\\par\n` + paragraph(text(profile.title)) + paragraph(contacts.join(' \\quad '));
}
function fill(template, values) {
  // Single-pass substitution also keeps placeholder-looking user text literal.
  return template.replace(/\{\{([A-Z_]+)\}\}/gu, (_, name) => {
    if (!Object.hasOwn(values, name)) throw new AppError('INVALID_TEMPLATE', '模板包含未知占位符', 500);
    return values[name];
  });
}

/** Render only validated data with references generated by resource preparation. */
export function renderResume(data, refs, template) {
  const checked = validateResumeData(data);
  if (!checked.ok) throw new AppError('INVALID_DATA', '简历数据无效', 400, { issues: checked.issues });
  if (!/^(?:\.\.\/)*resources\/font\/?$/u.test(refs.fontDir) ||
      (refs.logoFile !== null && !/^resources\/logo\.(?:png|jpg)$/u.test(refs.logoFile))) {
    throw new AppError('INVALID_RESOURCE', '构建资源引用无效', 500);
  }
  const paper = data.layout.paper === 'auto' ? (data.language === 'zh-CN' ? 'a4' : 'letter') : data.layout.paper;
  const compact = data.layout.density === 'compact';
  const profile = profileTex(data);
  const hasLogo = data.logo.mode !== 'hidden' && refs.logoFile !== null;
  const header = hasLogo
    ? `\\noindent\\begin{minipage}[c]{\\dimexpr\\linewidth-${data.logo.widthCm}cm-1em\\relax}\n${profile}\\end{minipage}\\hfill\n\\begin{minipage}[c]{${data.logo.widthCm}cm}\n\\raggedleft\\includegraphics[width=${data.logo.widthCm}cm,height=3.2cm,keepaspectratio]{${refs.logoFile}}\n\\end{minipage}\\par\n`
    : `\\begin{center}\n${profile}\\end{center}\n`;
  const sections = data.sectionOrder.filter(key => data.sections[key].enabled && data.sections[key].items.length)
    .map(key => `\\section{${TITLES[data.language][key]}}\n${data.sections[key].items.map(item => itemTex(key, item)).join('\n')}`).join('\n');
  const values = {
    PAPER: `${paper}paper`, FONT_SIZE: String(data.layout.fontSizePt), MARGIN: String(data.layout.marginMm),
    FONT_DIR: `${refs.fontDir.replace(/\/$/u, '')}/`, LANGUAGE: data.language,
    PAR_SKIP: compact ? '1pt' : '3pt', ITEM_SKIP: compact ? '1pt' : '3pt', SECTION_SKIP: compact ? '6pt' : '10pt',
    HEADER: header, SECTIONS: sections,
  };
  return { mainTex: fill(template.main, values), macrosTex: fill(template.macros, values) };
}
